// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIZsi1fYud8_uBcc-oYsaDU5Z2qCUx3aU',
    appId: '1:1044701920351:web:21ee49ee5e22a05d81afea',
    messagingSenderId: '1044701920351',
    projectId: 'pinjamalat-55c4b',
    authDomain: 'pinjamalat-55c4b.firebaseapp.com',
    storageBucket: 'pinjamalat-55c4b.firebasestorage.app',
    measurementId: 'G-S04EWCMKS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMTA6xxBf_Z6Bs1tJlmstEKslepTVcsHo',
    appId: '1:1044701920351:android:22edcd2babcd83ea81afea',
    messagingSenderId: '1044701920351',
    projectId: 'pinjamalat-55c4b',
    storageBucket: 'pinjamalat-55c4b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk39ImkQnZVCWF_3a2r7V5QzAfYv1GZ48',
    appId: '1:1044701920351:ios:92d7d571fa8504e381afea',
    messagingSenderId: '1044701920351',
    projectId: 'pinjamalat-55c4b',
    storageBucket: 'pinjamalat-55c4b.firebasestorage.app',
    iosBundleId: 'com.example.pinjamAlat',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk39ImkQnZVCWF_3a2r7V5QzAfYv1GZ48',
    appId: '1:1044701920351:ios:92d7d571fa8504e381afea',
    messagingSenderId: '1044701920351',
    projectId: 'pinjamalat-55c4b',
    storageBucket: 'pinjamalat-55c4b.firebasestorage.app',
    iosBundleId: 'com.example.pinjamAlat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIZsi1fYud8_uBcc-oYsaDU5Z2qCUx3aU',
    appId: '1:1044701920351:web:fb3b05ed9296816f81afea',
    messagingSenderId: '1044701920351',
    projectId: 'pinjamalat-55c4b',
    authDomain: 'pinjamalat-55c4b.firebaseapp.com',
    storageBucket: 'pinjamalat-55c4b.firebasestorage.app',
    measurementId: 'G-9C2VLYPMQ3',
  );
}
